let zoneProposition = document.querySelector(".zoneProposition");
let inputEcriture = document.getElementById("inputEcriture");
let btnValiderMot = document.getElementById("btnValiderMot");
let spanzoneScore = document.querySelector(".zoneScore span");
let Pourcentage = document.querySelector(".Pourcentage span");
let Sym = document.querySelector(".Sym");
let btnEnvoyerMail = document.querySelector("#btnEnvoyerMail");
let Form = document.querySelector("form");
let Nom = document.getElementById("nom");
let Email = document.getElementById("email");
let DomE=document.querySelector(".DomE")
let Dom=document.querySelector(".Dom")
